route:
  group_wait: 10s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 30s

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 30m

  # A default receiver
  receiver: "alertmanager-bot"

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.
  routes:
    - receiver: "alertmanager-bot"
      group_wait: 10s
      match_re:
        severity: critical|warning
      continue: true

receivers:
  - name: "alertmanager-bot"
    webhook_configs:
    - send_resolved: true
      url: 'http://telegram-bot:8080'
